version: '2'
 
services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
    links:
      - percona
    networks:
      - app-network
  percona:
    image: percona/percona-server:latest
    container_name: perconaserver
    environment:
      MYSQL_ROOT_PASSWORD: D4v1ds0n6514
      MYSQL_ROOT_HOST: 178.62.105.222
    ports:
      - "3306"
    volumes:
      # create volumes for use
      - /var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf
    command:
      # Workaround for no my.cnf in image
        - '--user=mysql'
    networks:
      - app-network
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'harleybartles.com -> http://app:5000'
      STAGE: 'production'
      #FORCE_RENEW: 'true'
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge