version: '2'
 
services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
    networks:
      - app-network
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'harleybartles.com -> http://app:5000'
      STAGE: 'production'
      #FORCE_RENEW: 'true'
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge