version: '3.1'

services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
    volumes:
      - appbuild:/app
    links:
      - db
    env_file: secrets.env
    environment:
      MYSQL_SERVER_NAME: perconaserver
      MYSQL_DATABASE: env_file.MYSQL_DATABASE
      MYSQL_USER: env_file.MYSQL_USER
      MYSQL_PASSWORD: env_file.MYSQL_PASSWORD

  db:
    image: percona/percona-server:latest
    container_name: perconaserver
    restart: always
    volumes:
      # create volumes for use
      - dbvol:/var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf
    env_file: secrets.env
    environment:
      MYSQL_ROOT_PASSWORD: env_file.MYSQL_PASSWORD
    ports:
      - "3306"
    command:
      # Workaround for no my.cnf in image
        - '--user=mysql'
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'harleybartles.com -> http://app:5000'
      STAGE: 'production'
      #FORCE_RENEW: 'true'

volumes:
  appbuild:
  dbvol: