version: '3.1'

services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - appbuild:/app
    links:
      - db
    env_file: 
      - authentication.env
      - mysqlconnection.env
      - environment.env
    #environment:
  db:
    image: percona/percona-server:latest
    container_name: perconaserver
    restart: always
    volumes:
      # create volumes for use
      - dbvol:/var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf
    env_file: mysqlconnection.env
    #environment:
    ports:
      - "3306"
    command:
      # Workaround for no my.cnf in image
        - '--user=mysql'
  https-portal:
    image: steveltn/https-portal:1
    container_name: httpsportal
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    env_file: httpsportal.env
    #environment:
      #FORCE_RENEW: 'true'

volumes:
  appbuild:
  dbvol:
