version: '3.1'
 
services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
    volumes:
      - appbuild:/app
    links:
      - db
    environment:
      MYSQL_SERVER_NAME: perconaserver

    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - app-network
  db:
    image: percona/percona-server:latest
    container_name: perconaserver
    restart: always
    volumes:
      # create volumes for use
      - dbvol:/var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306"
    command:
      # Workaround for no my.cnf in image
        - '--user=mysql'
    networks:
      - app-network
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'harleybartles.com -> http://app:5000'
      STAGE: 'production'
      #FORCE_RENEW: 'true'
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  appbuild:
  dbvol:

secrets:
  MYSQL_DATABASE:
    external: true
  MYSQL_USER=:
    external: true
  MYSQL_PASSWORD=:
    external: true